version: 2

project_name: gitti

before:
  hooks:
    # optional: you can add go mod tidy, tests, etc. here if you want
    - go mod tidy

builds:
  - id: gitti
    main: ./main.go
    binary: gitti
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w # strip debug symbols (smaller binary)
      - -X gitti/constant.APPVERSION=v{{.Version}}

archives:
  - id: gitti-archives
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE*
      - README.md
    name_template: >-
      {{- .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}

snapshot:
  version_template: "v{{ .Version }}-SNAPSHOT"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
      - "^Revert"
  groups:
    # 1. Features (The Catch-All)
    # Display Order: 0 (Top)
    # Logic: Any commit that does NOT match Fixes or Optimization falls here.
    - title: '🚀 Features'
      order: 0

    # 2. Bug Fixes
    # Display Order: 1
    # Regex: Case insensitive (?i). Matches 'fix', 'fixes', 'hotfix', 'bug'...
    - title: '🐛 Bug Fixes'
      regexp: "(?i)^.*(fix|hotfix|bug)"
      order: 1

    # 3. Optimization
    # Display Order: 2
    # Regex: Case insensitive (?i).
    # Matches:
    #  - 'opt' (covers 'opt:', 'optimize:', 'Optimization:', 'Optimisation:')
    #  - 'refactor' (covers 'refactor:', 'Refactoring:')
    #  - 'perf' (covers 'perf:', 'Performance:')
    #  - 'style'
    - title: '♻️ Optimization'
      regexp: "(?i)^.*(refactor|opt|perf|style)"
      order: 2

release:
  github:
    owner: gohyuhan
    name: gitti
  draft: false
  prerelease: auto
  extra_files:
    - glob: ./install.sh
    - glob: ./install.ps1
