package logging

const NEW_LOG_UPDATE = "NEW_LOG_UPDATE"

const (
	INFO  = "INFO"
	WARN  = "WARN"
	ERROR = "ERROR"
)

// the ops type constant
const (
	// EXPORT logging
	EXPORT_LOGGING_OPS = "EXPORT LOGGING"

	// BRANCH RELATED OPS
	GET_LATEST_BRANCH_INFO_OPS                   = "GET LATEST BRANCH INFO"
	CREATE_NEW_BRANCH_OPS                        = "CREATE NEW BRANCH"
	CREATE_NEW_BRANCH_AND_SWITCH_OPS             = "CREATE NEW BRANCH AND SWITCH"
	CREATE_NEW_BRANCH_BASED_ON_REMOTE_BRANCH_OPS = "CREATE NEW BRANCH BASED ON REMOTE BRANCH"
	STASH_ALL_FILE_OPS                           = "STASH ALL"
	STASH_INDIVIDUAL_FILE_OPS                    = "STASH INDIVIDUAL FILE"
	SWITCH_BRANCH_OPS                            = "SWITCH BRANCH"
	DELETE_LOCAL_BRANCH_OPS                      = "DELETE LOCAL BRANCH"

	// COMMIT RELATED OPS
	COMMIT_OPS                         = "COMMIT"
	AMEND_COMMIT_OPS                   = "AMEND COMMIT"
	GET_LATEST_COMMIT_MSG_AND_DESC_OPS = "GET LATEST COMMIT MSG AND DESCRIPTION"
	GIT_PUSH_OPS                       = "GIT PUSH"
	GIT_RESET_LATEST_COMMIT_OPS        = "GIT RESET LATEST COMMIT"
	GIT_RESET_TO_SELECTED_COMMIT_OPS   = "GIT RESET TO SELECTED COMMIT"

	// FILES RELATED OPS
	FILES_STATUS_OPS            = "FILES STATUS"
	FILE_DIFF_OPS               = "FILE DIFF"
	STAGE_OR_UNSTAGE_FILE_OPS   = "STAGE OR UNSTAGE FILE"
	STAGE_ALL_CHANGES_OPS       = "STAGE ALL CHANGES"
	UNSTAGE_ALL_CHANGES_OPS     = "UNSTAGE ALL CHANGES"
	STAGE_LINE_OPS              = "STAGE LINE"
	UNSTAGE_LINE_OPS            = "UNSTAGE LINE"
	DISCARD_FILE_CHANGES_OPS    = "DISCARD FILE CHANGES"
	DISCARD_LINE_CHANGES_OPS    = "DISCARD LINE CHANGES"
	RETRIEVE_ORIGINAL_FILE_OPS  = "RETRIEVE ORIGINAL FILE"
	REVERT_ORIGINAL_FILE_OPS    = "REVERT FILE"
	REVERT_NEWLY_NAMED_FILE_OPS = "REVERT NEWLY NAMED FILE"
	REMOVE_NEWLY_NAMED_FILE_OPS = "REMOVE NEWLY NAMED FILE"
	RESOLVE_CONFLICT_OPS        = "RESOLVE CONFLICT"

	// COMMIT LOG RELATED OPS
	COMMIT_LOG_OPS         = "COMMIT LOG"
	COMMIT_LOG_DETAIL_OPS  = "COMMIT LOG DETAIL"
	CHERRY_PICK_COMMIT_OPS = "CHERRY PICK COMMIT"

	// PULL RELATED OPS
	PULL_OPS = "PULL"

	// REMOTE RELATED OPS
	ADD_REMOTE_OPS               = "ADD REMOTE"
	CHECK_REMOTE_OPS             = "CHECK REMOTE"
	CHECK_REMOTE_SYNC_STATUS_OPS = "CHECK REMOTE SYNC STATUS"

	// STASH RELATED OPS
	GET_STASH_INFO = "GET STASH INFO"
	STASH_ALL      = "STASH ALL"
	STASH_FILE     = "STASH FILE"
	STASH_APPLY    = "STASH APPLY"
	STASH_POP      = "STASH POP"
	STASH_DROP     = "STASH DROP"
	STASH_DETAIL   = "STASH DETAIL"

	// UNIVERSAL STATE OPS
	SKIP     = "SKIP"
	ABORT    = "ABORT"
	CONTINUE = "CONTINUE"

	// ACUQUIRE GIT LOCK
	ACQUIRE_GIT_LOCK = "ACQUIRE_GIT_LOCK"
)
