package git

const (
	PUSH               = "PUSH"
	FORCEPUSHSAFE      = "FORCEPUSHSAFE"
	FORCEPUSHDANGEROUS = "FORCEPUSHDANGEROUS"
)

const (
	NEWBRANCH          = "NEWBRANCH"
	NEWBRANCHANDSWITCH = "NEWBRANCHANDSWITCH"
)
