package git

const (
	GIT_BRANCH_UPDATE                          = "GIT_BRANCH_UPDATE"
	GIT_COMMIT_OUTPUT_UPDATE                   = "GIT_COMMIT_OUTPUT_UPDATE"
	GIT_AMEND_COMMIT_OUTPUT_UPDATE             = "GIT_AMEND_COMMIT_OUTPUT_UPDATE"
	GIT_REMOTE_PUSH_OUTPUT_UPDATE              = "GIT_REMOTE_PUSH_OUTPUT_UPDATE"
	GIT_PULL_OUTPUT_UPDATE                     = "GIT_PULL_OUTPUT_UPDATE"
	GIT_REBASE_OUTPUT_UPDATE                   = "GIT_REBASE_OUTPUT_UPDATE"
	GIT_STASH_UPDATE                           = "GIT_STASH_UPDATE"
	GIT_COMMITLOG_UPDATE                       = "GIT_COMMITLOG_UPDATE"
	GIT_REFLOG_UPDATE                          = "GIT_REFLOG_UPDATE"
	GIT_FILES_STATUS_UPDATE                    = "GIT_FILES_STATUS_UPDATE"
	GIT_REMOTE_SYNC_STATUS_AND_UPSTREAM_UPDATE = "GIT_REMOTE_SYNC_STATUS_AND_UPSTREAM_UPDATE"
	GIT_EDIT_LINE_DETAILS_AND_FILES_UPDATE     = "GIT_EDIT_LINE_DETAILS_AND_FILES_UPDATE"
	GIT_STATE_UPDATE                           = "GIT_STATE_UPDATE"
	GIT_FETCH                                  = "GIT_FETCH" // user triggered, not from daemon
	GIT_TAG_UPDATE                             = "GIT_TAG_UPDATE"
	GIT_TAG_PUSH_OUTPUT_UPDATE                 = "GIT_TAG_PUSH_OUTPUT_UPDATE"
	GIT_TAG_FETCH_OUTPUT_UPDATE                = "GIT_TAG_FETCH_OUTPUT_UPDATE"
	GIT_REMOTE_UPDATE                          = "GIT_REMOTE_UPDATE"
	GIT_WORKTREE_UPDATE                        = "GIT_WORKTREE_UPDATE"
)
