package git

const (
	GENERAL_GIT_UPDATE       = "GENERAL_GIT_UPDATE"
	GIT_COMMIT_OUTPUT_UPDATE = "GIT_COMMIT_OUTPUT_UPDATE"
	GIT_COMMIT_LOG_UPDATE    = "GIT_COMMIT_LOG_UPDATE"
	GIT_FILES_STATUS_UPDATE  = "GIT_FILES_STATUS_UPDATE"
)
