package git

const (
	GIT_BRANCH_UPDATE              = "GIT_BRANCH_UPDATE"
	GIT_COMMIT_OUTPUT_UPDATE       = "GIT_COMMIT_OUTPUT_UPDATE"
	GIT_AMEND_COMMIT_OUTPUT_UPDATE = "GIT_AMEND_COMMIT_OUTPUT_UPDATE"
	GIT_REMOTE_PUSH_OUTPUT_UPDATE  = "GIT_REMOTE_PUSH_OUTPUT_UPDATE"
	GIT_PULL_OUTPUT_UPDATE         = "GIT_PULL_OUTPUT_UPDATE"
	GIT_STASH_UPDATE               = "GIT_STASH_UPDATE"
	GIT_LOG_UPDATE                 = "GIT_LOG_UPDATE"
	GIT_FILES_STATUS_UPDATE        = "GIT_FILES_STATUS_UPDATE"
)
